# Generated by Django 5.0.14 on 2025-11-18 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_nguoidung_avatar_url_nguoidung_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nguoidung',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/default.png', null=True, upload_to='avatars/', verbose_name='avatar'),
        ),
    ]
