# Generated by Django 5.0.14 on 2025-11-18 15:00

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_nguoidung_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nguoidung',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.doi_ten_avatar, verbose_name='avatar'),
        ),
    ]
