# Generated by Django 5.0.14 on 2025-11-14 17:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DanhMuc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DoiTuong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=100)),
                ('icon_url', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuanHuyen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TienIch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=100)),
                ('icon_url', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TinhThanh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PhuongXa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=100)),
                ('quan_huyen_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phongtro.quanhuyen')),
            ],
        ),
        migrations.CreateModel(
            name='TinDang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tieu_de', models.CharField(max_length=255)),
                ('mo_ta', models.TextField(blank=True, null=True)),
                ('dia_chi_chi_tiet', models.CharField(max_length=255)),
                ('gia_moi_thang', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dien_tich_m2', models.FloatField()),
                ('trang_thai_duyet', models.BooleanField(default=False)),
                ('hoat_dong', models.BooleanField(default=True)),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('ngay_cap_nhat', models.DateTimeField(auto_now=True)),
                ('chu_tro_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tin_dang_cua_chu_tro', to=settings.AUTH_USER_MODEL)),
                ('danh_muc_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='phongtro.danhmuc')),
                ('doi_tuong', models.ManyToManyField(blank=True, to='phongtro.doituong')),
                ('phuong_xa_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='phongtro.phuongxa')),
                ('quan_huyen_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='phongtro.quanhuyen')),
                ('tien_ich', models.ManyToManyField(blank=True, to='phongtro.tienich')),
                ('tinh_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='phongtro.tinhthanh')),
            ],
        ),
        migrations.CreateModel(
            name='BaoCao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ly_do', models.TextField()),
                ('trang_thai', models.CharField(choices=[('cho_xu_ly', 'Chờ xử lý'), ('da_xu_ly', 'Đã xử lý'), ('bo_qua', 'Bỏ qua')], default='cho_xu_ly', max_length=20)),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('nguoi_bao_cao_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cac_bao_cao', to=settings.AUTH_USER_MODEL)),
                ('tin_dang_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cac_bao_cao', to='phongtro.tindang')),
            ],
        ),
        migrations.CreateModel(
            name='AnhTinDang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=255)),
                ('la_anh_dai_dien', models.BooleanField(default=False)),
                ('tin_dang_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cac_anh', to='phongtro.tindang')),
            ],
        ),
        migrations.AddField(
            model_name='quanhuyen',
            name='tinh_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phongtro.tinhthanh'),
        ),
        migrations.CreateModel(
            name='TinYeuThich',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_luu', models.DateTimeField(auto_now_add=True)),
                ('nguoi_thue_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tin_dang_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phongtro.tindang')),
            ],
            options={
                'unique_together': {('nguoi_thue_id', 'tin_dang_id')},
            },
        ),
    ]
