# Generated by Django 5.0.14 on 2025-11-17 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phongtro', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doituong',
            old_name='icon_url',
            new_name='icon',
        ),
        migrations.RenameField(
            model_name='tienich',
            old_name='icon_url',
            new_name='icon',
        ),
        migrations.RemoveField(
            model_name='anhtindang',
            name='image_url',
        ),
        migrations.AddField(
            model_name='anhtindang',
            name='image',
            field=models.ImageField(default=1, upload_to='tin_dang/'),
            preserve_default=False,
        ),
    ]
