# Generated by Django 5.0.14 on 2025-11-20 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phongtro', '0002_rename_icon_url_doituong_icon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tindang',
            name='trang_thai_duyet',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
